name: CI Pipeline PIMS

on:
  push:
    branches: [ "main" ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

    # 🔹 1. Récupérer le code
    - name: Checkout code
      uses: actions/checkout@v3

    # ───────── FRONTEND (Angular) ─────────
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18

    - name: Install dependencies (Angular)
      run: |
        cd front
        npm install

    - name: Build Angular app
      run: |
        cd front
        npm run build -- --configuration production

  # ───────── BACKEND (Spring Boot) ─────────
    - name: Setup Java 21
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: 21

    - name: Give execute permission to mvnw
      run: |
        cd pims-plateform
        chmod +x mvnw

    - name: Build Spring Boot  (skip tests)
      run: |
        cd pims-plateform
        ./mvnw clean install -DskipTests

    - name: Run backend tests
      run: |
        cd pims-plateform
        ./mvnw test


    # ───────── SECURITY CHECK (BONUS 🔥) ─────────
    - name: Audit frontend dependencies
      run: |
        cd front
        npm audit --audit-level=high